### ISSUE TITLE
main.py file not working

### ISSUE THREAD

**Issue by UppaLouva** [Alikhalkhali/programs-watcher#6]
When I run this:

`python3 main.py`

I am encountering this error:

`Traceback (most recent call last):
  File "/home/Tools/programs-watcher/main.py", line 41, in <module>
    check_bugcrowd(tmp_dir, discord_webhook, first_time, db, platforms['bugcrowd'])
  File "/home/Tools/programs-watcher/modules/platforms/bugcrowd.py", line 17, in check_bugcrowd
    programURL = "https://bugcrowd.com"+program["program_url"]
                                        ~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'program_url'
`
Can you help? How can I solve that ?

**Comment by Bhaskar-jat** [comment]
Yeah man same here.

**Comment by Alikhalkhali** [comment]
Hi UppaLouva and Bhaskar-jat,

Apologies for the delay in response. Thank you for letting us know. The issues have been resolved, and you can now proceed to use the service.

Additionally, there is an upcoming update that hopefully will make up for the delay. To stay informed about the update sooner, you can follow me on Twitter at ali_khalkhali0.
